version: '3.3'

services:
   db:
     image: amazon/dynamodb-local
     ports:
       - "8000:8000"

   tests:
     depends_on:
       - db
     build: ./test/
     user: ${HOST_UID_GID}
     environment:
        AWS_DEFAULT_REGION: "us-east-1"
     volumes:
       - ./:/code
     command: ./test/test.sh
     stop_signal: SIGINT
     links:
      - db