pipeline {
    agent any
    stages {
        stage('Clean'){    
            steps {
                deleteDir()
                sh 'printenv'
            }
        }
        stage('Checkout code'){    
            steps {
            checkout scm
            }
        }

        stage('SetUp'){
            steps{
                // Setup Virtualenv for testing
                echo "Setup Virtualenv for testing"
                sh '''
                    python3 -m venv sandbox
                    source sandbox/bin/activate 
                    ls -l 
                    pip install -r todos/requirements.txt -q
                    pip install -r requirements.txt -q
                    pip install -r test/requirements.txt -q

                '''
            }
        }
        stage('Test'){
            steps{
                    // Static program analysis -> radon
                    echo 'Make some cool static program analysis wich radon. IIs the code enought simple to understand?'
                sh '''
                    source sandbox/bin/activate 
                    export HOST_UID_GID=$(id -u):$(id -g)
                    docker-compose  -f test/docker-compose.yml  up   --abort-on-container-exit
                '''
            }
            
        }
        
        stage('Build & Package'){
            steps{
                sh 'sam build & sam package ----s3-bucket es-unir-staging-s3-63265-artifacts'
            }
        }

    }
    
        post {
        always {
            junit 'output/*.xml'
        }
    }

}

