pipeline {
    agent any
    stages {
        stage('Clean'){    
            steps {
                deleteDir()
                sh 'printenv'
            }
        }

        stage('SetUp'){
            steps{
                // Setup Virtualenv for testing
            }
        }
        stage('Test'){
            steps{
                dir("todo-list-aws/test") {
                    // Static program analysis -> radon
                    echo 'Make some cool static program analysis wich radon. IIs the code enought simple to understand?'
                }
            }
        }
    }
}
